### ISSUE TITLE
Combined TemperatureService device with valueAirPressure failed

### ISSUE THREAD

**Issue by nordblick2** [Samfox2/homebridge-domotiga#17]
Hey (again),
i tried to configure a combined sensor with a valueAirPressure-Item. Without valueAirPressure it works very well, but adding it results in a "null pointer"-exception (see stack trace below). In sample config file this value is mentioned, so i guess it should work well. Any idea where that error comes from and what i have to change? 

accessories and persistent folder were cleared completely (rm /*) before starting homebridge - first start shows no errors but also no data, restarting homebridge results in the error below) 

Config file looks like following:
```
{
	"name": "Gartensensor.",
	"service": "TemperatureSensor",
	"command": "/home/nbo/bin/sensors.json.sh -p $value -f plain",
	"device": "aussensensor",
	"valueTemperature": "T",
	"valueHumidity": "H",
	"valueBattery": "B",
	"valueAirPressure": "P",
	"batteryVoltage": 3.313,
	"batteryVoltageLimit": 3.000,
}
```

First start after clearing accessories and persistent folder ("getting pressure" part is missing here) :
```
[2/4/2017, 11:16:09 PM] [dev] Initializing platform accessory 'Gartensensor.'...
[2/4/2017, 11:16:09 PM] [dev] ADD PRESSURE CHARACTERISTICS:  Gartensensor.
[2/4/2017, 11:16:09 PM] [dev] Gartensensor.: getting temperature...
[2/4/2017, 11:16:09 PM] [dev] Gartensensor.: getting relative humidity...
[2/4/2017, 11:16:09 PM] [dev] Gartensensor.: getting battery level...
[2/4/2017, 11:16:09 PM] [dev] Initializing platform accessory 'Dose 1'...
```

Exception on second start:
```
/usr/local/lib/node_modules/homebridge-domotiga/index.js:1169
                primaryservice.getCharacteristic(EveAirPressure).getValue();
                                                                ^

TypeError: Cannot read property 'getValue' of undefined
    at DomotigaPlatform.getInitState (/usr/local/lib/node_modules/homebridge-domotiga/index.js:1169:65)
    at DomotigaPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-domotiga/index.js:485:10)
    at DomotigaPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-domotiga/index.js:183:38)
    at emitNone (events.js:86:13)
    at API.emit (events.js:185:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
nbo@chaos:/home/nbo/projects/homebridge-domotiga>
```

Line numbers may differ...

**Comment by nordblick2** [comment]
By the way: The error occurs also for FakeEve*-Services. Seems that all intern defined services can't be loaded.

**Comment by Samfox2** [comment]
Hmm, that's really strange as it was working before. I'll have a look at it...

**Comment by Samfox2** [comment]
Fixed (finally)
