### ISSUE TITLE
homebridge-domotiga crashes when trying to get humidity

### ISSUE THREAD

**Issue by wwolkers** [Samfox2/homebridge-domotiga#8]
Opening details of a temperature module from the iOS home app homebridge crashes:

[11/1/2016, 11:41:02 PM] [Sensor Slaapkamer] getting CurrentRelativeHumidity for Sensor Slaapkamer
/usr/lib/node_modules/homebridge-domotiga/index.js:247
                callback(null, data.result.values[item].value);
                                                       ^

TypeError: Cannot read property 'value' of undefined
    at /usr/lib/node_modules/homebridge-domotiga/index.js:247:56
    at /usr/lib/node_modules/homebridge-domotiga/node_modules/jsonrequest/lib/index.js:57:9
    at opt_callback (/usr/lib/node_modules/homebridge-domotiga/node_modules/tinyreq/lib/index.js:53:9)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-domotiga/node_modules/tinyreq/lib/index.js:85:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Samfox2** [comment]
Please make sure that "valueHumidity" is defined in your "config.json". If it is still not working, please try every other value number that is defined at your domotiga device. I remember there was an issue that domotiga deliveres it`s values in a wrong order (maybe the order of value generation or sth. like that).

**Comment by Samfox2** [comment]
Is it working for you now?

**Comment by Samfox2** [comment]
Close this as it seems to work now.
